# Generated by Django 2.1.2 on 2018-10-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default='admin@gmail.com', max_length=254),
        ),
    ]
