# Generated by Django 2.1.2 on 2018-11-22 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('sum', models.IntegerField()),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFlower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='Shop',
        ),
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(default='https://fbcd.co/images/products/06fcb49e43e6c7960e48ddff1ebe3428_resize.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='orderflower',
            name='flower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Flower'),
        ),
        migrations.AddField(
            model_name='orderflower',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shop'),
        ),
    ]
