# Generated by Django 2.1.2 on 2018-11-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181122_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='image',
            field=models.ImageField(default='https://fbcd.co/images/products/06fcb49e43e6c7960e48ddff1ebe3428_resize.png', upload_to=''),
        ),
    ]
