# Generated by Django 2.1.2 on 2018-11-24 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_flower_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='flowers',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='sum',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='price',
        ),
        migrations.AddField(
            model_name='customer',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Shop'),
        ),
        migrations.AddField(
            model_name='shopflower',
            name='price',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
